version: "3.8"
services:

  api:
    build:
      dockerfile: Dockerfile
      context: ./apis/${API_PATH}
      target: development
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: ${API_CONTAINER_NAME}
    volumes:
      - "./apis/${API_PATH}/src:/opt/app/src"
      - "./apis/${API_PATH}/test:/opt/app/test"
      - "./apis/${API_PATH}/nest-cli.json:/opt/app/nest-cli.json"
      - "./apis/${API_PATH}/tsconfig.json:/opt/app/tsconfig.json"
      - "./apis/${API_PATH}/tsconfig.build.json:/opt/app/tsconfig.build.json"
      - "./apis/${API_PATH}/.env:/opt/app/.env"
    command: ./node_modules/.bin/nest start --watch
    environment: 
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: 1hard_to_guess_secret7890a
      PORT: ${NEST_SERVER_PORT}
    # ports:
    #   - ${NEST_SERVER_PORT}:${NEST_SERVER_PORT}
    #   # debugging port
    #   - 9229:9229
    network_mode: host
    # networks:
    #   - neo4j_net
    depends_on:
      neo4j:
        condition: service_healthy

  client:
    build:
      dockerfile: Dockerfile
      context: ./clients/${CLIENT_PATH}
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: ${CLIENT_CONTAINER_NAME}
    volumes:
      - "./clients/${CLIENT_PATH}/src:/opt/app/src"
      - "./clients/${CLIENT_PATH}/angular.json:/opt/app/angular.json"
      - "./clients/${CLIENT_PATH}/karma.conf.js:/opt/app/karma.conf.js"
      - "./clients/${CLIENT_PATH}/tsconfig.app.json:/opt/app/tsconfig.app.json"
      - "./clients/${CLIENT_PATH}/tsconfig.spec.json:/opt/app/tsconfig.spec.json"
      - "./clients/${CLIENT_PATH}/tsconfig.json:/opt/app/tsconfig.json"
    command: sh -c "./node_modules/.bin/ng serve --port 4200 --host 0.0.0.0 --poll 2000"
    ports:
      - 4200:4200
      # debugging port
      # - 49153:49153

# #############################
# ######### neo4j #############
# #############################

  # neo4j-seeder:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./datas/${NEO4J_PATH}/seeder-container
  #   container_name: neo4j-seeder
  #   environment:
  #     NEO4J_HOSTNAME: ${NEO4J_HOSTNAME}
  #     NEO4J_USERNAME: ${NEO4J_USERNAME}
  #     NEO4J_PASSWORD: ${NEO4J_PASSWORD}
  #     NEO4J_PORT: ${NEO4J_PORT}
  #     NEO4J_BOLT_PORT: ${NEO4J_BOLT_PORT}
  #   volumes:
  #     - "./datas/${NEO4J_PATH}/seeder-container/to-import:/import"
  #   networks:
  #     - neo4j_net
  #   depends_on:
  #     neo4j:
  #       condition: service_healthy
  
  neo4j:
    build:
      dockerfile: Dockerfile
      context: ./datas/${NEO4J_PATH}
    hostname: ${NEO4J_HOSTNAME}
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4J_dbms_memory_heap_max__size: ${NEO4J_MEM_HEAP}
      NEO4J_dbms_connector_bolt_advertised__address: "0.0.0.0:${NEO4J_BOLT_PORT}"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_dbms.shell.enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_dbms.default_listen_address: 0.0.0.0
      NEO4J_dbms_default__database: ${NEO4J_DATABASE}
      # NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # NEO4J_apoc_initializer_cypher: "CALL apoc.cypher.runFile('file:///apoc.cypher_query.cypher')"
      # NEO4JLABS_PLUGINS: '["apoc"]'
      # NEO4J_dbms_logs_debug_level: DEBUG
      # NEO4J_AUTH: none
      NEO4J_kafka_bootstrap_servers: broker:9093
      # NEO4J_dbms.security.procedures.whitelist: apoc.coll.*,apoc.load.*,apoc.cypher.*
    ports:
      - "7474:${NEO4J_PORT}"  # Go to http://localhost:7474/browser/ after bootstrapping
      - "7687:${NEO4J_BOLT_PORT}"
    volumes:
      - "./datas/${NEO4J_PATH}/neo4j-runtime/db/data:/data"
      - "./datas/${NEO4J_PATH}/neo4j-runtime/logs:/logs"
      - "./datas/${NEO4J_PATH}/neo4j-runtime/import:/import"
      - "./datas/${NEO4J_PATH}/neo4j-runtime/plugins:/plugins"
    networks:
      - neo4j_net
    healthcheck:
      test: [ "CMD", "/var/lib/neo4j/bin/cypher-shell", "-u", "${NEO4J_USERNAME}", "-p", "${NEO4J_PASSWORD}", "MATCH () RETURN count(*) as count LIMIT 1" ]
      interval: 3s
      timeout: 3s
      retries: 50
      start_period: 40s

# # #############################
# # ######### keycloak ##########
# # #############################

  kc-postgres:
    image: postgres
    container_name: kc-postgres
    environment:
      - POSTGRES_USER=${KC_DB_USER}
      - POSTGRES_DATABASE=${KC_DB_DATABASE}
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
    volumes:
      - "./keycloak/postgres_data:/var/lib/postgresql/data"
    networks:
      - neo4j_net
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d keycloak -U keycloak"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: keycloak
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    # add plugins for hot deployment in running in KC
    #   - ./plugins:/opt/jboss/keycloak/standalone/deployments/
    volumes:
      - "./keycloak/realms/import:/tmp/import"
    command: start-dev
    # entrypoint: /opt/keycloak/bin/kc.sh start --auto-build
    env_file:
      - ./keycloak/.env
    environment:
      KC_FEATURES:
        authorization
        token-exchange
        docker
        impersonation
        scripts
        upload-scripts
        web-authn
        client-policies
        dynamic-scopes
    networks:
      - neo4j_net
    ports:
      - 8080:8080
    depends_on:
      kc-postgres:
        condition: service_healthy


######################
####### Kafka ########
######################

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    logging:
      driver: none
    networks:
      - neo4j_net

  broker:
    image: confluentinc/cp-kafka
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
    - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:9093
      # workaround if we change to a custom name the schema_registry fails to start
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      # CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    logging:
      driver: none
    networks:
      - neo4j_net

  schema_registry:
    image: confluentinc/cp-schema-registry
    hostname: schema_registry
    container_name: schema_registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:9093'
    logging:
      driver: none
    networks:
      - neo4j_net
  
  connect:
    image: confluentinc/cp-kafka-connect
    hostname: connect
    container_name: connect
    depends_on:
      - zookeeper
      - broker
      - schema_registry
    ports:
      - "8083:8083"
    volumes:
      - ./kafka/plugins:/tmp/connect-plugins
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:9093'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONNECT_PLUGIN_PATH: /usr/share/java,/tmp/connect-plugins
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=DEBUG,org.I0Itec.zkclient=DEBUG,org.reflections=ERROR
    # command:
    #  - bash
    #  - -c
    #  - |
    #    confluent-hub install --no-prompt neo4j/kafka-connect-neo4j:5.0.0
    #     /etc/confluent/docker/run
    logging:
      driver: none
    networks:
      - neo4j_net

  control-center:
    image: confluentinc/cp-enterprise-control-center
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - broker
      - schema_registry
      - connect
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:9093'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    logging:
      driver: none
    networks:
      - neo4j_net

networks:
  neo4j_net:
    driver: bridge