version: "3.8"
services:

  api:
    image: my_api:latest
    build:
      dockerfile: Dockerfile
      context: ./apis/${API_PATH}
      target: development
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: ${API_CONTAINER_NAME}
    volumes:
      - "./apis/${API_PATH}/src:/opt/app/src"
      - "./apis/${API_PATH}/test:/opt/app/test"
      - "./apis/${API_PATH}/nest-cli.json:/opt/app/nest-cli.json"
      - "./apis/${API_PATH}/tsconfig.json:/opt/app/tsconfig.json"
      - "./apis/${API_PATH}/tsconfig.build.json:/opt/app/tsconfig.build.json"
      - "./apis/${API_PATH}/.env:/opt/app/.env"
    command: ./node_modules/.bin/nest start --watch
    environment: 
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: 1hard_to_guess_secret7890a
      PORT: ${NEST_SERVER_PORT}
    ports:
      - ${NEST_SERVER_PORT}:${NEST_SERVER_PORT}
      # debugging port
      - 9229:9229
    networks:
      - fullstack_net
    depends_on:
      neo4j:
        condition: service_healthy

  client:
    image: my_client:latest
    build:
      dockerfile: Dockerfile
      context: ./clients/${CLIENT_PATH}
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: ${CLIENT_CONTAINER_NAME}
    volumes:
      - "./clients/${CLIENT_PATH}/src:/opt/app/src"
      - "./clients/${CLIENT_PATH}/angular.json:/opt/app/angular.json"
      - "./clients/${CLIENT_PATH}/karma.conf.js:/opt/app/karma.conf.js"
      - "./clients/${CLIENT_PATH}/tsconfig.app.json:/opt/app/tsconfig.app.json"
      - "./clients/${CLIENT_PATH}/tsconfig.spec.json:/opt/app/tsconfig.spec.json"
      - "./clients/${CLIENT_PATH}/tsconfig.json:/opt/app/tsconfig.json"
    command: sh -c "./node_modules/.bin/ng serve --port 4200 --host 0.0.0.0 --poll 2000"
    ports:
      - 4200:4200
      # debugging port
      - 49153:49153

networks:
  fullstack_net:
    driver: bridge