version: "3.8"
services:

#############################
######### neo4j #############
#############################
  
  neo4j:
    build:
      dockerfile: Dockerfile
      context: ./datas/${NEO4J_PATH}
    hostname: ${NEO4J_HOSTNAME}
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4J_dbms_memory_heap_max__size: ${NEO4J_MEM_HEAP}
      NEO4J_dbms_connector_bolt_advertised__address: "0.0.0.0:${NEO4J_BOLT_PORT}"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_dbms.shell.enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_dbms.default_listen_address: 0.0.0.0
      NEO4J_dbms_default__database: ${NEO4J_DATABASE}
      # NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # NEO4J_apoc_initializer_cypher: "CALL apoc.cypher.runFile('file:///apoc.cypher_query.cypher')"
      # NEO4JLABS_PLUGINS: '["apoc"]'
      # NEO4J_dbms_logs_debug_level: DEBUG
      NEO4J_kafka_bootstrap_servers: broker:9093
      # NEO4J_dbms.security.procedures.whitelist: apoc.coll.*,apoc.load.*,apoc.cypher.*
    ports:
      - "7474:${NEO4J_PORT}"  # Go to http://localhost:7474/browser/ after bootstrapping
      - "7687:${NEO4J_BOLT_PORT}"
    volumes:
      - "./datas/${NEO4J_PATH}/neo4j-runtime/db/data:/data"
      - "./datas/${NEO4J_PATH}/neo4j-runtime/logs:/logs"
      - "./datas/${NEO4J_PATH}/neo4j-runtime/import:/import"
      - "./datas/${NEO4J_PATH}/neo4j-runtime/plugins:/plugins"
    networks:
      - fullstack_net
    healthcheck:
      test: [ "CMD", "/var/lib/neo4j/bin/cypher-shell", "-u", "${NEO4J_USERNAME}", "-p", "${NEO4J_PASSWORD}", "MATCH () RETURN count(*) as count LIMIT 1" ]
      interval: 3s
      timeout: 3s
      retries: 50
      start_period: 40s

networks:
  fullstack_net:
    driver: bridge
