version: v0.6.0-alpha.2

dsn: postgres://test:test@postgresdb:5432/test?sslmode=disable&max_conns=20&max_idle_conns=4

dev: true

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
      debug: true
      allow_credentials: true
      options_passthrough: true
      max_age: 0
      allowed_origins:
        - http://127.0.0.1:4200
        - http://kratos.local:4200 # added this to /etc/hosts -> i had cors problems and with this it works, not sure how
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Content-Type
        - X-Session-Token
        - Cookie
        - Origin
      exposed_headers:
        - Content-Type
        - Content-Length
        - Content-Range
        - User-Agent
        - Cache-Control
        - Set-Cookie
        - Authorization
        - X-Session-Token
        - X-CSRF-Token
        - X-XSRF-Token
        - Cookie
        - Origin
        - Access-Controll-Allow-Origins
        - Access-Controll-Allow-Headers
        - Access-Controll-Allow-Methods
  admin:
    base_url: http://127.0.0.1:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4200/
  allowed_return_urls:
    - http://127.0.0.1:4200/login
    - http://127.0.0.1:4200/
    - http://127.0.0.1:4200/dashboard
  methods:
    password:
      enabled: true
    oidc:
      enabled: true
    link:
      enabled: true
  flows:
    error:
      ui_url: http://127.0.0.1:4200/error
    settings:
      ui_url: http://127.0.0.1:4200/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4200/recovery
      after:
        default_browser_return_url: http://127.0.0.1:4200/login
    verification:
      enabled: true
      ui_url: http://127.0.0.1:4200/verify
      after:
        default_browser_return_url: http://127.0.0.1:4200/
    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4200/login
    login:
      ui_url: http://127.0.0.1:4200/login
      lifespan: 10m
    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4200/register
      after:
        password:
          hooks:
            - hook: session
          default_browser_return_url: http://127.0.0.1:4200/login
        default_browser_return_url: http://127.0.0.1:4200/login
        oidc:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - deVuA0F46ZWFh3v4wGPVEQDlVXMbLKzG

session:
  lifespan: 24h
  cookie:
    domain: http://127.0.0.1:4200
    same_site: Lax

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json


## identity ##
#
identity:
  ## All JSON Schemas for Identity Traits ##
  #
  # Note that identities that used the "default_schema_url" field in older kratos versions will be corrupted unless you specify their schema url with the id "default" in this list.
  #
  # Examples:
  # - - id: customer
  #     url: base64://ewogICIkc2NoZW1hIjogImh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDcvc2NoZW1hIyIsCiAgInR5cGUiOiAib2JqZWN0IiwKICAicHJvcGVydGllcyI6IHsKICAgICJiYXIiOiB7CiAgICAgICJ0eXBlIjogInN0cmluZyIKICAgIH0KICB9LAogICJyZXF1aXJlZCI6IFsKICAgICJiYXIiCiAgXQp9
  #   - id: employee
  #     url: https://foo.bar.com/path/to/employee.traits.schema.json
  #   - id: employee-v2
  #     url: file://path/to/employee.v2.traits.schema.json
  # 
  # Set this value using environment variables on
  # - Linux/macOS:
  #    $ export IDENTITY_SCHEMAS=<value>
  # - Windows Command Line (CMD):
  #    > set IDENTITY_SCHEMAS=<value>
  #
  schemas:
    - id: user
      url: file:///etc/config/kratos/identity.schema.json

  ## The default Identity Schema ##
  #
  # This Identity Schema will be used as the default for self-service flows. Its ID needs to exist in the "schemas" list.
  #
  # Default value: default
  #
  # Set this value using environment variables on
  # - Linux/macOS:
  #    $ export IDENTITY_DEFAULT_SCHEMA_ID=<value>
  # - Windows Command Line (CMD):
  #    > set IDENTITY_DEFAULT_SCHEMA_ID=<value>
  #
  default_schema_id: "user"  

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
    from_name: test
    from_address: office@test.org
